# Generated by Django 5.0.6 on 2024-07-02 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_productos_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='proveedor',
        ),
    ]
