# Generated by Django 5.0.6 on 2024-07-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_remove_productos_proveedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['nombre'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='proovedor',
            options={'ordering': ['nombre'], 'verbose_name': 'Proovedor', 'verbose_name_plural': 'Proovedores'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
    ]
