# Generated by Django 5.0.6 on 2024-07-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_cliente_options_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(max_length=12),
        ),
    ]
